name: Python Tests
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - get_movies
          - add_or_update_movie
          - delete_movie
    name: Test ${{ matrix.function }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd functions/${{ matrix.function }}
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          cd functions/${{ matrix.function }}
          source venv/bin/activate
          pytest --disable-warnings
